# fly.toml app configuration file generated for django-todo-api on 2023-12-04T22:13:54-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "django-todo-api"
primary_region = "gdl"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
